piVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  template:
    spec:
      containers:
      - name: init-container
        image: zozoh94/flask-vue-kubernetes/init:v1.1
        env:
          - name: POSTGRES_HOST
            value: "postgres"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-password
                key: POSTGRES_ROOT_PASSWORD
      restartPolicy: Never
  backoffLimit: 4